### ISSUE TITLE
Cancel selection button

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [rohanjariwala03/drop_down_search_field#24]
Can a button ( X ) be included in the textField when a selection is made so that when onTap it will remove the selection? This should also call the onSelectionChanged by default

**Comment by rohanjariwala03** [comment]
@Priyantha-Kingslake It is really easy task to include cancel button but the issue is lot of people don't want cancel button. But what you can do is on your side you can add cancel button and clear the selected dropdown when pressed.

**Comment by rohanjariwala03** [comment]
@Priyantha-Kingslake It is really easy task to include cancel button but the issue is lot of people don't want cancel button. But what you can do is on your side you can add cancel button and clear the selected dropdown when pressed.

**Comment by Priyantha-Kingslake** [comment]
Yes. I have managed it by my side currently. Just thought it would be a nice feature if this is available as a optional feature. Completely clearing a search bar before a new search is a fairly common scenario, right?

**Comment by rohanjariwala03** [comment]
@Priyantha-Kingslake Yes, you're right. You need to clear before adding new search. If you can make a Pull request with the changes you want then it would be amazing for me. Feel free to contribute.
