### ISSUE TITLE
On Click of 5th item or some time 6th or 7th item click don't work in suggestion box and instead click on back textfields available under the suggestion box

### ISSUE THREAD

**Issue by ArslanKhan99** [rohanjariwala03/drop_down_search_field#29]
On Click of 5th item or some time 6th or 7th item click don't work in suggestion box and instead click on back textfields available under the suggestion box

**Comment by ArslanKhan99** [comment]
Observe now if dropdown position is center or below the screen its doest not allow to click on any item

**Comment by ArslanKhan99** [comment]
I am using the dropdown inside a dialog

**Comment by rohanjariwala03** [comment]
@ArslanKhan99 can you share a screen recording or something, so, I have exact reference of what you are talking about. Thanks

**Comment by ArslanKhan99** [comment]
Surprisingly Its working today. I changed nothing making video and its working now.

**Comment by ArslanKhan99** [comment]
Attaching video occurred again.

https://github.com/rohanjariwala03/drop_down_search_field/assets/62021808/47657cf7-7cd0-49dc-92dd-2ff0074d8216

**Comment by ArslanKhan99** [comment]
instead if clicking on option in suggestion box clicked on back fields

**Comment by rohanjariwala03** [comment]
@ArslanKhan99 this issue will be fixed soon. Thanks for reporting.

**Comment by rohanjariwala03** [comment]
@ArslanKhan99  it should be fix now. You need to use new version of this package. and pass `ignoreAccessibleNavigation: true`.
If issue persist, then please open this Issue again.

**Comment by kszymiczek-propbase** [comment]
@rohanjariwala03 Problem still exists in 1.0.4, because fix made in PR #30, was reverted in #31 
There is problem with catching clicks by field under the suggestions, and also with scrolling lists of suggestion.
