### ISSUE TITLE
Calling suggestionCallback without text change

### ISSUE THREAD

**Issue by siiimaay** [rohanjariwala03/drop_down_search_field#34]
Hi, 

I’m trying to make a pagination so that it renders once again when scroll controller achieved to end, Is there any workaround to trigger suggestion callback without text change? Thank you

**Comment by rohanjariwala03** [comment]
@siiimaay right now that feature is not supported but it's really great idea. I can try to implement this soon.

**Comment by siiimaay** [comment]
will be great, thanks!
