### ISSUE TITLE
AppBar, suggestions not showing

### ISSUE THREAD

**Issue by itisnajim** [rohanjariwala03/drop_down_search_field#42]
When inside an AppBar the suggestions not showing!

**Comment by itisnajim** [comment]
i'm talking about CupertinoNavigationBar, material one its working

**Comment by rohanjariwala03** [comment]
@itisnajim Please share screen recording of issue and code snippets.

**Comment by rohanjariwala03** [comment]
@itisnajim Closing this issue for now as there is no significant details. You can reopen at anytime.
