### ISSUE TITLE
While tapping on suggestions item, Item beneath the suggestion box is being tapped. 

### ISSUE THREAD

**Issue by manandharsudhir** [rohanjariwala03/drop_down_search_field#43]
https://github.com/rohanjariwala03/drop_down_search_field/assets/33796281/383a4783-6d4f-473d-8650-82905e1e7985

**Comment by rohanjariwala03** [comment]
@manandharsudhir Sorry for the delayed reply and Thanks for using Package.

In my latest version I've added property called `hideSuggestionsOnKeyboardHide` So, you can pass `hideSuggestionsOnKeyboardHide: false,`. So, suggestions won't be tapped in back.

Make sure your version number is more than `1.0.4`. 

Closing this issue. Let me know if you still have that issue after adding above property and feel free to reopen this issue.
