### ISSUE TITLE
Fetching suggestions shouldn't be dependent on the suggestion box being mounted in the UI

### ISSUE THREAD

**Issue by andreasmpet** [rohanjariwala03/drop_down_search_field#45]
Hi! From the code it seems that there is no fetching of suggestions done if the suggestion list is not mounted in the widget tree.

The suggestions should be fetched when the search text changes as long as the field has focus

The current behavior makes it so that if you can end up in situations where the suggestions stop showing alltogether if you've dismissed the suggestion box once.

https://github.com/rohanjariwala03/drop_down_search_field/assets/79078/355bca45-8b9c-4a65-b31c-a488c4c209e4

In case you missed it, I clicked the mouse outside the suggestion box to dismiss it, and then started typing again.

I'm gonna fork the repo and see if I can fix this.

**Comment by andreasmpet** [comment]
It's a bit too much for me to rewrite this thing, but I have found a workaround for now.
I added the _focusNode?.unfocus() call when the suggestion list is closed with an outside tap.

```
        child: TextFieldTapRegion(
            onTapOutside: (e) {
              if (widget.suggestionsBoxDecoration.closeSuggestionBoxWhenTapOutside) {
                if (this._suggestionsBox?.isOpened ?? false) {
                  this._focusNode?.unfocus();
                  this._suggestionsBox?.close();
                }
              }
            },
```

**Comment by rohanjariwala03** [comment]
@andreasmpet Thanks for pointing out the mistake. It would be nice if you can contribute to this repository if not then will try to add the fixes you suggested soon.

**Comment by anantnimbalkar** [comment]
> It's a bit too much for me to rewrite this thing, but I have found a workaround for now. I added the _focusNode?.unfocus() call when the suggestion list is closed with an outside tap.
> 
> ```
>         child: TextFieldTapRegion(
>             onTapOutside: (e) {
>               if (widget.suggestionsBoxDecoration.closeSuggestionBoxWhenTapOutside) {
>                 if (this._suggestionsBox?.isOpened ?? false) {
>                   this._focusNode?.unfocus();
>                   this._suggestionsBox?.close();
>                 }
>               }
>             },
> ```

@andreasmpet can you please share. where to do this change?

**Comment by andreasmpet** [comment]
> > It's a bit too much for me to rewrite this thing, but I have found a workaround for now. I added the _focusNode?.unfocus() call when the suggestion list is closed with an outside tap.
> > ```
> >         child: TextFieldTapRegion(
> >             onTapOutside: (e) {
> >               if (widget.suggestionsBoxDecoration.closeSuggestionBoxWhenTapOutside) {
> >                 if (this._suggestionsBox?.isOpened ?? false) {
> >                   this._focusNode?.unfocus();
> >                   this._suggestionsBox?.close();
> >                 }
> >               }
> >             },
> > ```
> 
> @andreasmpet can you please share. where to do this change?

Just search for `if (widget.suggestionsBoxDecoration.closeSuggestionBoxWhenTapOutside)` and you'll find it.

That said, in the end I just used the built in DropdownMenu to achieve what I wanted.
