### ISSUE TITLE
Suggestion Box Not scrolling and Not selecting values

### ISSUE THREAD

**Issue by aravind-m-s** [rohanjariwala03/drop_down_search_field#48]
I am not able to select any value or scroll the suggestions box when the direction of the suggestion box is up ( AxisDIrection.up )
This issue is already mentioned in the issues tab. Please refer #44 . 

I am attaching a small set of code for reproducing the issue.

`class TestWidget extends StatelessWidget {`
`const TestWidget({super.key});`

`@OverRide`
`Widget build(BuildContext context) {`
`return Scaffold(`

`body: Column(`
`children: [`
`Expanded(child: SizedBox()),`
`DropDownSearchFormField(`
`autoFlipDirection: true,`
`autoFlipListDirection: false,`
`autoFlipMinHeight: 100,`
`onSuggestionSelected: (suggestion) {},`
`itemBuilder: (context, itemData) {`
`return Padding(`
`padding: const EdgeInsets.all(24.0),`
`child: Text(itemData),`
`);`
`},`
`suggestionsCallback: (pattern) {`
`return [`
`"Hello 1",`
`"Hello 2",`
`"Hello 3",`
`"Hello 4",`
`"Hello 5",`
`"Hello 6",`
`"Hello 7",`
`"Hello 8",`
`"Hello 9",`
`"Hello 10",`
`"Hello 11",`
`"Hello 12",`
`"Hello 13",`
`"Hello 14",`
`"Hello 15",`
`"Hello 16",`
`"Hello 17",`
`"Hello 18",`
`"Hello 19",`
`"Hello 20",`
`"Hello 21",`
`"Hello 22",`
`"Hello 23",`
`"Hello 24",`
`"Hello 25",`
`"Hello 26",`
`"Hello 27",`
`"Hello 28",`
`"Hello 29",`
`"Hello 30",`
`];`
`},`
`),`
`],`
`),`
`);`
`}`
`}`

**Comment by PrakashkumarM** [comment]
I have the same issue as well.

**Comment by rohanjariwala03** [comment]
@aravind-m-s @PrakashkumarM I’m currently tied up with other tasks. If you can investigate and resolve the bug, please go ahead and submit a pull request. If you’re unable to fix it, I’ll take a look after October 3rd.

**Comment by rohanjariwala03** [comment]
@PrakashkumarM @aravind-m-s This issue should be fixed once I'll merge my Pull Request.
